Monitor User_Status y Contextos correspondientes
Dagasfi/SUA_ImplementacionBROS pull request #19
Opened 2021-05-24 22:13 UTC by Andresalejan

Muchachos por favor revisen mi magnifico e impresionante aporte, 🗡️

2021-05-24 22:36 UTC, Dagasfi commented on Contexto.DriverSleeping/src/contexto/driversleeping/ContextoDriverSleeping.java
> +		this.setDriverSleeping(true);
Empieza dormido? xdé

2021-05-24 22:48 UTC, Dagasfi requested changes
Cambios pendientes

2021-05-24 22:48 UTC, Dagasfi commented on Contexto.ManosVolante/src/contexto/manosvolante/ContextoManosVolante.java
> +		this.addImplementedInterface(IDriverSleepingContext.class.getName());
```IDriverSleepingContext``` deberia ser ```IManosVolanteContext```

2021-05-24 22:48 UTC, Dagasfi commented on Contexto.UbicacionDriver/src/contexto/ubicaciondriver/ContextoUbicacionDriver.java
> +		this.setUbicacionDriver(1);
Todo futuro: 
cambiar el ````1``` por constantes

2021-05-24 22:48 UTC, Dagasfi commented on monitor.UserStatus/src/monitor/userstatus/ControladorUserStatus.java
> +			}
Añadir un nuevo contexto para poder leer los estados de "looking ahead" del usuario.

2021-05-25 00:11 UTC, Andresalejan commented on AutonomousCar.interfaces/src/sua/autonomouscar/context/interfaces/IMirandoAlFrente.java
> +}
Interfaz de MirandoAlFrente

2021-05-25 00:12 UTC, Andresalejan commented on Contexto.MirandoAlFrente/src/contexto/mirandoalfrente/Activator.java
> +}
Activador de MirandoAlFrente

2021-05-25 00:12 UTC, Andresalejan commented on Contexto.MirandoAlFrente/src/contexto/mirandoalfrente/ContextoMirandoAlFrente.java
> +}
Contexto de MirandoAlFrente

2021-05-25 00:14 UTC, Andresalejan commented on Simulacion.RoadStatus/src/simulacion/roadstatus/Activator.java
> +
Añadí la simulación de MirandoAlFrente, ManosAlVolante y UbicacionDriver

2021-05-25 00:17 UTC, Dagasfi reviewed
Todo okey

2021-05-25 00:25 UTC, merged